### PR TITLE
Electric Slimaloo d1.0

### PR DESCRIPTION
**Pull request by KrabSpider**
With the increase in popularity of xenobiology, and the general ability to turn conversion based gamemodes into curbstomp should the players desire to do so with non-implantable slaves that are bound to their summoner, legion's of mobs that generally can't be controlled from afar, and mobs that can reproduce and spawn mobs that have murderbone restrictions removed. I felt it necessary to make it harder to obtain such feats with what you start with and a few minutes of research.

#### Changelog

:cl:
tweaks:  makes slimefires now require 10 units of plasma. Slime explosions now require 5 plasma. One isn't as damaging, the other renders an area unsafe and increases the pressure of a room. 
tweaks: sentience potions and adamantine golems can only be obtained with strange reagent. I will be working 
tweaks: Mind transfer potions now require unstable mutation toxin, no, diluting your beaker will not make you spawn one.
tweaks: increased plasma cost for red slimes to 5 units, in contrast to one. 
tweaks: makes custom golems now require uranium.

/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
You made a pull request on your own fork, which won't do anything. You'd want to submit this PR to yogstation13/yogstation. Instead, you submitted it to krabspider/yogstation---exp. 

Also, your changelog has errors. Make the prefix "tweak", not "tweaks". Tweaks isn't a valid prefix.

**Comment by KrabSpider** [comment]
Thanks...

**Comment by Partheo** [comment]
Nice

**Comment by KrabSpider** [comment]
Partheo I just needed the change for copy and paste because I was in a rush. Don't judge me

**Pull request merged**
